[project]
name = "redis-provider"
version = "0.1.0"
description = "Shared Redis Provider for PaperTerrace"
dependencies = [
    "redis>=5.0.0",
]
requires-python = ">=3.12"

[tool.hatch.build.targets.wheel]
packages = ["."]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
