apiVersion: v2
name: paperterrace
description: A Helm chart for PaperTerrace application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: redis
    version: 18.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
